### ISSUE TITLE
As a Developer, the read me might not be clear

### ISSUE THREAD

**Issue by Matt-Lepley** [dustinlakin/twitch-rb#14]
I'm currently trying to use this gem and am running into issues finding out how to get the `client_id` and  `secret_key` in the first step. Are these in the twitch dashboard or found by other means.

Sorry, the only way I knew how to ask a question was to make an issue. Feel free to close if this is not the correct way.

**Comment by catuss-a** [comment]
@Matt-Lepley you need to register your app on twitch.tv to get the client and secret and set a redirect url

**Comment by Matt-Lepley** [comment]
@catuss-a Thank you very much for letting me know that, I was completely unaware.

**Comment by catuss-a** [comment]
@Matt-Lepley you're welcome :+1:
