### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by samurailink3** [dustinlakin/twitch-rb#15]
Having a license file would be helpful here so developers know how they can use this code. GitHub made [a helpful site to help developers pick a license for their code](http://choosealicense.com/).

**Comment by dustinlakin** [comment]
Thanks @samurailink3, I am going to add in a MIT license file. Appreciate the input!

**Comment by dustinlakin** [comment]
Added in commit a49bd814bf890ef474eb6d31a5464eea4c70641e
