### ISSUE TITLE
Bad Request (400) error: "No client id specified"

### ISSUE THREAD

**Issue by TheRPunkt** [dustinlakin/twitch-rb#28]
Hello,
I was trying a bit around with this API and just wanted to get information of a specific user.
I used: 

```
@twitch = Twitch.new(client_id: @client_id)
@twitch.user "day9tv"
```

so this code returns this:

`{:body=>{"error"=>"Bad Request", "status"=>400, "message"=>"No client id specified"}, :response=>400}`

Sooo I do not really know what I'm doing wrong. However I think that I missed something. Can somebody help?

**Comment by RKushnir** [comment]
Just got this myself. From the code, this is not implemented. The only place where `client_id` is  used is authentication.

**Comment by TheRPunkt** [comment]
Alright, so I have to find another solution for that. Thank you :)

**Comment by RKushnir** [comment]
@TheRPunkt You can try your luck with this branch https://github.com/dustinlakin/twitch-rb/pull/26

**Comment by TheRPunkt** [comment]
@RKushnir Thanks, I will look into it
