### ISSUE TITLE
Helix API update

### ISSUE THREAD

**Issue by Drakula2k** [dustinlakin/twitch-rb#35]
Just leaving it here in case anyone needs it https://github.com/Crowd9/twitch-rb/commit/f4bfbc19abdb02a5329e4e9bf9b8e7132d1a6783

I haven't tested all of the methods there, only a few that I use. 
This repo seems to be abandoned, so I'm not doing a proper pull request with specs and docs updates.

**Comment by AlexWayfer** [comment]
We left this repo as at outdated Kraken API.

Probably @dustinlakin should archive it.

Although #34 is still not merged…

Anyway.

For the Helix API there are [`twitch-api`](https://github.com/mauricew/ruby-twitch-api) and other gems.
